<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Paggi\\Traits\\' => array($vendorDir.'/paggi/sdk/lib/Traits'),
    'Paggi\\' => array($vendorDir.'/paggi/sdk/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir.'/doctrine/inflector/lib/Doctrine/Common/Inflector'),
    'Curl\\' => array($vendorDir.'/php-curl-class/php-curl-class/src/Curl'),
);
