<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1814475da2000df930a6c95fa80396af
{
    public static $prefixLengthsPsr4 = array(
        'P' => array(
            'Paggi\\Traits\\' => 13,
            'Paggi\\' => 6,
        ),
        'D' => array(
            'Doctrine\\Common\\Inflector\\' => 26,
        ),
        'C' => array(
            'Curl\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array(
        'Paggi\\Traits\\' => array(
            0 => __DIR__.'/..'.'/paggi/sdk/lib/Traits',
        ),
        'Paggi\\' => array(
            0 => __DIR__.'/..'.'/paggi/sdk/lib',
        ),
        'Doctrine\\Common\\Inflector\\' => array(
            0 => __DIR__.'/..'.'/doctrine/inflector/lib/Doctrine/Common/Inflector',
        ),
        'Curl\\' => array(
            0 => __DIR__.'/..'.'/php-curl-class/php-curl-class/src/Curl',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1814475da2000df930a6c95fa80396af::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1814475da2000df930a6c95fa80396af::$prefixDirsPsr4;
        }, null, ClassLoader::class);
    }
}
